on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Build & Deploy to ACI
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login to Azure'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Create Azure Registery'
          run: az acr create --resource-group mirangithubdemo --name mirangithubdemoregistry --sku Basic
        
        - name: 'Build & Push'
          uses: azure/docker-login@v1
          with:
            login-server: mirangithubdemoregistry.azurecr.io
            username: ${{ secrets.AZURE_USERNAME }}
            password: ${{ secrets.AZURE_PASSWORD }}
        - run: |
            docker build . -t hello-world:${{ github.sha }}
            docker tag hello-world:${{ github.sha }} mirangithubdemoregistry.azurecr.io/samples/hello-world:${{ github.sha }}
            docker push mirangithubdemoregistry.azurecr.io/samples/hello-world:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: mirangithubdemo
            dns-name-label: helloworlddevtest
            image: mirangithubdemoregistry.azurecr.io/samples/hello-world:${{ github.sha }}
            cpu: 1
            memory: 1
            registry-username: ${{ secrets.AZURE_USERNAME }}
            registry-password: ${{ secrets.AZURE_PASSWORD }}
            name: helloworlddev
            location: 'central india'
